<a href="https://colab.research.google.com/github/YKochura/cv-kpi/blob/main/math/ndarray.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Manipulation with Ndarray

Importing `numpy` module  

In [1]:
import numpy as np

Create a vector and query its attributes

In [2]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

(12,)

In [4]:
x.size

12

More ways to construct arrays

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [7]:
np.random.normal(0, 1, size=(3, 4))

array([[-0.36488904,  0.35244516, -0.2764291 , -1.02793515],
       [-2.01988054, -0.14495897, -0.98441473,  0.05356182],
       [-0.66435861,  0.04349139,  0.24525069, -1.80923276]])

Elemental-wise operators

In [8]:
x = np.array([1, 2, 4, 8])
y = np.ones_like(x) * 2
print('x =', x)
print('y =', y)
print('x + y =', x + y)
print('x - y =', x - y)
print('x * y =', x * y)
print('x ** y =', x ** y)
print('x / y =', x / y)

x = [1 2 4 8]
y = [2 2 2 2]
x + y = [ 3  4  6 10]
x - y = [-1  0  2  6]
x * y = [ 2  4  8 16]
x ** y = [ 1  4 16 64]
x / y = [0.5 1.  2.  4. ]


Matrix multiplication.

In [9]:
x = np.arange(12).reshape((3,4))
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.dot(x, y.T)

array([[ 18,  20,  10],
       [ 58,  60,  50],
       [ 98, 100,  90]])

In [10]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
y

array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [12]:
y.T

array([[2, 1, 4],
       [1, 2, 3],
       [4, 3, 2],
       [3, 4, 1]])

Concatenate arrays along a particular axis.

In [13]:
np.concatenate([x, y], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [14]:
 np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])

Broadcast Mechanism

In [15]:
a = np.arange(3).reshape((3, 1))
b = np.arange(2).reshape((1, 2))
print('a:\n', a)
print('b:\n', b)

a:
 [[0]
 [1]
 [2]]
b:
 [[0 1]]


In [16]:
a + b

array([[0, 1],
       [1, 2],
       [2, 3]])

Indexing and Slicing


In [17]:
print('x =\n', x)

x =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print('x[-1] =\n', x[-1])

x[-1] =
 [ 8  9 10 11]


In [19]:
print('x[1:3] =\n', x[1:3])

x[1:3] =
 [[ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print('x[1:3, 2:4] =\n', x[1:3, 2:4])

x[1:3, 2:4] =
 [[ 6  7]
 [10 11]]


In [21]:
print('x[1,2] =', x[1,2])

x[1,2] = 6


In [22]:
print(type(x))

<class 'numpy.ndarray'>
